baseURL = "https://MFToonS.netlify.com"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "0"
summaryLength = "0"
theme = "meghna-hugo"
title = ""
[Languages.en]
contentDir = ""
copyright = ""
home = ""
languageCode = ""
languageName = ""
weight = ""
[Languages.fr]
contentDir = ""
copyright = ""
home = ""
languageCode = ""
languageName = ""
weight = ""
[menu]
main = []
[params]
author = ""
description = ""
google_analytics_id = ""
logo = ""
post_share = false
social = []
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = ""
map_latitude = ""
map_longitude = ""
map_marker = ""
[params.plugins]
css = []
js = []
[params.preloader]
enable = false
preloader = ""
